[package]
name = "aoc23-day-05"
version = "0.1.0"
edition = "2021"
default-run = "part1"

[[bin]]
name = "part1"

[[bin]]
name = "part2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
